#version: "3.8"

services:
  httpd:
    #image: php:8.1-apache # Apache with PHP 8.1
    build: . # This tells Docker Compose to use the Dockerfile in the current directory
    container_name: apache-php
    ports:
      - "8080:80" # Expose port 80 on container to port 8080 on host
    volumes:
      - ./html:/var/www/html # Copy local files to the Apache container
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Root password
      MYSQL_DATABASE: ${MYSQL_DATABASE} # Database name
      #MYSQL_USER: ${MYSQL_USER} # MySQL user
      #MYSQL_PASSWORD: ${MYSQL_PASSWORD} # MySQL password
    ports:
      - "3306:3306" # Expose MySQL port
    volumes:
      - db_data:/var/lib/mysql # Store MySQL data persistently
      - ./db-init:/docker-entrypoint-initdb.d # Initialize the database with scripts

volumes:
  db_data:
    driver: local # Persistent MySQL data storage
